---
# handlers file for microsocks
- name: microsocks_reload_systemd
  systemd:
    daemon_reload: yes

- name: microsocks_reload_service
  systemd:
    name: "{{ microsocks_service_name }}"
    state: restarted
